[project]
name = "image-to-art"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dearpygui>=2.1.0",
    "numpy>=2.2.6",
    "onnxruntime>=1.22.1",
    "opencv-python>=4.12.0.88",
    "psutil>=7.0.0",
]
